apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
<<<<<<< HEAD
  cluster: projects/my-gcp-project/locations/us-central1-c/clusters/cluster-1

=======
  cluster: projects/my-gcp-project/locations/us-central1-c/clusters/cluster-1
>>>>>>> 51e1dba (Updated files with GCP-project-name)
