apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: cicd
description: Deploy app1 and app2 to GKE
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
    - targetId: prod
      profiles: []